"""Genera el contenido estático de la propuesta B; no requiere dependencias."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).parent / 'dist'
GENERAL = 'https://wa.link/h2jnnc'
SERVICES = [
    dict(slug='deudas-insolvencia', name='Deudas e insolvencia', image='01-deudas-insolvencia', wa='uwryis',
         title='¿Las deudas superan lo que puedes pagar?',
         brief='Recupera claridad sobre tus obligaciones y conoce las alternativas que podrían aplicar a tu situación.',
         intro='Cuando cada ingreso ya tiene destino y los cobros no paran, decidir se vuelve más difícil. Puedes empezar por poner tus obligaciones en orden y entender qué caminos vale la pena evaluar.',
         situations=['Los pagos mensuales superan tu capacidad actual y no sabes qué priorizar.', 'Tienes obligaciones con varios acreedores y necesitas una visión completa de tu situación.', 'Quieres saber si una negociación o un proceso de insolvencia podría ser una alternativa para ti.'],
         outcomes=[('Tu punto de partida', 'Revisamos deudas, ingresos y documentos para entender tu capacidad de pago y las dificultades que enfrentas.'), ('Las alternativas', 'Evaluamos las opciones de manejo de tus obligaciones y si tiene sentido estudiar una posible insolvencia.'), ('Una ruta para decidir', 'Te explico qué implica cada alternativa, qué información falta y cuál podría ser el siguiente paso.')],
         prepare='Ten a mano una relación de tus deudas, los pagos que realizas, tus ingresos y las comunicaciones de cobro que hayas recibido. Si la información está incompleta, empezamos por identificar qué falta.',
         faq=[('¿La insolvencia es una opción para cualquier persona?', 'Depende de las condiciones de cada situación. Primero se revisan tus obligaciones, tu capacidad de pago y la información necesaria para evaluar si esta vía resulta aplicable.'), ('¿La asesoría garantiza que desaparezcan mis deudas?', 'No. La orientación busca que comprendas las alternativas y sus implicaciones. Cualquier resultado depende de las condiciones del caso y del procedimiento que corresponda.'), ('¿Puedo consultar si todavía estoy pagando?', 'Sí. Puedes solicitar una revisión de tu situación para comprender tus opciones antes de tomar nuevas decisiones sobre tus obligaciones.')],
         cta='Quiero revisar mis deudas', close='Empieza por entender tus opciones.', alt='Mujer organizando facturas y haciendo cuentas en casa'),
    dict(slug='reportes-crediticios', name='Reportes crediticios', image='02-reportes-crediticios', wa='ku1tfy',
         title='¿Un reporte negativo está limitando tus opciones de crédito?',
         brief='Entiende qué información aparece en tu historial y si hay motivos para solicitar una revisión.',
         intro='Que una solicitud de crédito no avance puede dejarte con más preguntas que respuestas. Revisemos el reporte y sus antecedentes para entender qué está ocurriendo y qué puedes hacer.',
         situations=['Encuentras una obligación o un dato que no reconoces en tu historial.', 'Ya realizaste un pago y tienes dudas sobre la información que sigue apareciendo.', 'Necesitas orientación para consultar o reclamar información relacionada con un reporte.'],
         outcomes=[('Qué dice tu reporte', 'Revisamos la información disponible y los documentos relacionados con la obligación.'), ('Qué conviene aclarar', 'Identificamos posibles inconsistencias y los soportes que hacen falta para estudiar una reclamación.'), ('Cómo solicitar la revisión', 'Te explico las gestiones que podrían corresponder y el alcance del acompañamiento en tu caso.')],
         prepare='Reúne el reporte que quieres revisar, los comprobantes de pago y las respuestas de la entidad, si los tienes. No compartas contraseñas ni códigos de acceso: para comenzar basta con contar qué información te preocupa.',
         faq=[('¿Todo reporte negativo se puede eliminar?', 'No se puede asegurar eso. Primero hay que revisar la información, sus antecedentes y si existen fundamentos para solicitar una corrección o realizar otra gestión.'), ('¿Pueden garantizarme que me aprueben un crédito?', 'No. La aprobación depende de la entidad que evalúa la solicitud. El acompañamiento se enfoca en revisar la información reportada y las actuaciones que puedan corresponder.'), ('¿Qué pasa si no reconozco la deuda?', 'Cuéntame qué información aparece y qué comunicaciones has recibido. Eso permite definir qué antecedentes y soportes es necesario revisar.')],
         cta='Quiero revisar mi reporte', close='Entiende qué hay detrás de tu reporte.', alt='Hombre revisando información financiera en un portátil'),
    dict(slug='embargos-cobros', name='Embargos y cobros', image='03-embargos-cobros', wa='twk37q',
         title='¿Recibiste una notificación de cobro o embargo y no sabes qué hacer?',
         brief='Comprende el documento que recibiste, en qué estado está el asunto y qué opciones debes evaluar.',
         intro='Una carta de cobro o una notificación puede hacerte pensar de inmediato en tu sueldo, tu cuenta o tus bienes. El primer paso es entender qué recibiste y qué atención necesita tu situación.',
         situations=['Te llegó una comunicación y no distingues si es un cobro o una actuación judicial.', 'Tienes conocimiento de un proceso y necesitas revisar sus documentos.', 'Te preocupa una medida sobre tus ingresos o tus bienes y buscas orientación para actuar.'],
         outcomes=[('Qué está ocurriendo', 'Revisamos la comunicación, quién la emite y los antecedentes que tengas del asunto.'), ('Qué requiere atención', 'Identificamos el estado de la situación y los puntos que deben revisarse para definir una respuesta.'), ('Qué opciones evaluar', 'Te explico las alternativas que puedan corresponder y el alcance de una eventual representación.')],
         prepare='Ten disponible la notificación completa, la fecha en que la recibiste y los documentos de la obligación. Si conoces el número del proceso o has recibido otras comunicaciones, inclúyelos al explicar tu caso.',
         faq=[('¿Una llamada de cobro significa que ya existe un embargo?', 'Es necesario distinguir entre las comunicaciones de cobro y los documentos de un proceso. Revisar lo que recibiste permite entender tu situación concreta.'), ('¿La asesoría puede levantar un embargo de inmediato?', 'No se puede prometer un levantamiento ni un tiempo de respuesta sin estudiar el caso. Primero se revisan el proceso, los documentos y las actuaciones que puedan corresponder.'), ('¿Qué debo contar en el primer mensaje?', 'Indica qué recibiste, cuándo lo recibiste y qué te preocupa. Con esa información podemos coordinar la revisión de los documentos.')],
         cta='Quiero revisar la notificación', close='Comprende tu situación antes de decidir.', alt='Hombre leyendo una comunicación con documentos y llaves sobre la mesa'),
    dict(slug='recuperacion-cartera', name='Recuperación de cartera', image='04-recuperacion-cartera', wa='b59gk4',
         title='¿Te deben dinero y necesitas reclamar el pago?',
         brief='Revisa los soportes de la deuda y las vías disponibles para reclamar lo que te deben.',
         intro='Has cumplido con tu parte, pero el pago no llega. Mientras insistes, se afectan tus cuentas y tus planes. Revisemos qué respalda la obligación y qué camino puedes considerar para reclamarla.',
         situations=['Entregaste un producto o prestaste un servicio y el pago sigue pendiente.', 'Prestaste dinero y los compromisos de pago no se han cumplido.', 'Has intentado cobrar y necesitas evaluar una gestión formal o una posible reclamación.'],
         outcomes=[('El respaldo de tu cobro', 'Revisamos contratos, facturas, comprobantes y comunicaciones relacionados con la obligación.'), ('Las vías disponibles', 'Evaluamos si conviene considerar un acuerdo, una gestión de cobro o una actuación judicial.'), ('El alcance de la gestión', 'Hablamos de los pasos, los costos del servicio y los factores que pueden influir en la recuperación.')],
         prepare='Reúne los documentos que respaldan la deuda, el monto pendiente, las fechas acordadas y las comunicaciones con la persona o empresa que te debe. Indica también si hubo abonos o acuerdos posteriores.',
         faq=[('¿Puedo consultar si no tengo un contrato firmado?', 'Sí. Podemos revisar qué documentos, comprobantes o comunicaciones existen y qué permiten acreditar. La viabilidad de una gestión depende de esa revisión.'), ('¿Es necesario demandar desde el principio?', 'La vía adecuada depende del caso. Primero se estudian los antecedentes, los soportes disponibles y las posibilidades de acuerdo o reclamación.'), ('¿Se puede garantizar la recuperación del dinero?', 'No. El resultado depende de varios factores, entre ellos los soportes de la obligación y las condiciones del deudor. La revisión permite valorar esas dificultades antes de avanzar.')],
         cta='Quiero revisar una deuda a mi favor', close='Dale una dirección clara a tu reclamación.', alt='Emprendedora revisando facturas en su negocio'),
    dict(slug='contratos-patrimonio', name='Contratos y patrimonio', image='05-contratos-patrimonio', wa='a2imqi',
         title='¿Necesitas claridad antes de firmar o decidir sobre tus bienes?',
         brief='Entiende tus compromisos, identifica puntos de atención y toma decisiones con mejor información.',
         intro='Una firma puede comprometer dinero, tiempo y bienes que has construido con esfuerzo. Antes de decidir, conviene que entiendas qué aceptas y qué necesitas aclarar.',
         situations=['Vas a firmar un contrato y hay condiciones que no entiendes o te generan dudas.', 'Necesitas dejar claros los compromisos de un acuerdo personal o comercial.', 'Tienes una inquietud sobre documentos o acuerdos relacionados con tus bienes.'],
         outcomes=[('Qué estás acordando', 'Revisamos el objeto del contrato, las obligaciones y los puntos relevantes para tu decisión.'), ('Qué merece atención', 'Identificamos ambigüedades, compromisos y condiciones que conviene aclarar o discutir.'), ('Cómo avanzar', 'Definimos si necesitas una revisión, ajustes al documento o acompañamiento para estructurar el acuerdo.')],
         prepare='Ten a mano el contrato o borrador completo, sus anexos y una explicación de lo que quieres lograr. Si se trata de un bien, cuéntame cuál es la operación y qué documentos tienes disponibles.',
         faq=[('¿Puedo consultar antes de tener un contrato listo?', 'Sí. Podemos conversar sobre el acuerdo que necesitas y definir qué información hace falta para establecer el alcance de su elaboración o revisión.'), ('¿También puedo consultar si ya firmé?', 'Sí. La revisión puede ayudarte a comprender los compromisos asumidos y a evaluar una inquietud o dificultad concreta relacionada con el acuerdo.'), ('¿La revisión evita cualquier problema futuro?', 'Ninguna revisión elimina todos los riesgos. Su propósito es ayudarte a identificar puntos relevantes, aclarar compromisos y decidir con mejor información.')],
         cta='Quiero revisar mi contrato o acuerdo', close='Que tu próxima firma sea una decisión informada.', alt='Mujer revisando un contrato junto a un profesional'),
    dict(slug='familia-sucesiones', name='Familia y sucesiones', image='06-familia-sucesiones', wa='0xlmp0',
         title='¿Una situación familiar necesita un camino claro?',
         brief='Encuentra orientación para una separación, un asunto con tus hijos o los trámites de una herencia.',
         intro='Cuando una decisión involucra a tu familia, las dudas jurídicas se mezclan con lo que sientes. Mereces un espacio para explicar lo que ocurre y entender las opciones con calma.',
         situations=['Estás considerando una separación o un divorcio y necesitas entender qué asuntos revisar.', 'Tienes inquietudes sobre alimentos, custodia o acuerdos relacionados con tus hijos.', 'Tras el fallecimiento de un familiar, necesitas orientación sobre una sucesión.'],
         outcomes=[('Lo que necesitas resolver', 'Escuchamos tu situación e identificamos los asuntos familiares y patrimoniales que requieren atención.'), ('Las opciones del caso', 'Revisamos los documentos, los acuerdos existentes y los puntos en los que hay diferencias.'), ('Un siguiente paso claro', 'Te explico las alternativas y definimos el acompañamiento que necesitas para avanzar.')],
         prepare='Empieza por contar qué está pasando y qué necesitas resolver. Si tienes acuerdos anteriores, comunicaciones o documentos relacionados con la situación, podemos definir cuáles conviene revisar.',
         faq=[('¿Puedo consultar aunque mi familia todavía no esté de acuerdo?', 'Sí. La orientación inicial permite entender tu situación, identificar las diferencias y revisar las alternativas disponibles.'), ('¿Puedo recibir orientación sobre varios asuntos a la vez?', 'Sí. Si una separación involucra acuerdos sobre hijos o bienes, podemos identificar los temas relacionados y organizar la revisión de cada uno.'), ('¿Qué información necesito para una sucesión?', 'En la primera conversación identificamos la información sobre el familiar fallecido, las personas involucradas y los bienes conocidos para definir qué documentación hace falta.')],
         cta='Quiero orientación sobre mi familia', close='Un paso claro en un momento sensible.', alt='Tres mujeres de distintas generaciones conversando con una carpeta en la mesa')
]

def wa(url, label, cls='button gold'):
    return f'<a class="{cls}" href="{url}" target="_blank" rel="noopener noreferrer">{label}</a>'

def head(title, description, base=''):
    return f'''<!doctype html><html lang="es"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)} · Simón Abogado</title><meta name="description" content="{escape(description, quote=True)}"><meta name="robots" content="noindex,nofollow">
<link rel="icon" href="{base}assets/favicon.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{base}styles.css"><link rel="stylesheet" href="{base}sections.css"><link rel="stylesheet" href="{base}services.css"><link rel="stylesheet" href="{base}footer.css"><link rel="stylesheet" href="{base}motion.css"></head><body>
<a class="skip" href="#contenido">Ir al contenido</a><header class="header" id="inicio-pagina" tabindex="-1"><a class="brand" href="{base or './'}" aria-label="Simón Abogado, inicio"><img src="{base}assets/logo.png" alt="Simón Abogado. Compromiso que garantiza tu confianza." width="2172" height="724"></a><button class="menu-toggle" aria-expanded="false" aria-controls="menu">Menú <span aria-hidden="true">☰</span></button><nav id="menu" aria-label="Principal"><a href="{base}#servicios">Encuentra orientación</a><a href="{base}#simon">Conoce a tu abogado</a>{wa(GENERAL, 'Cuéntame tu situación', 'nav-cta')}</nav></header>'''

def footer(base='', contact_url=GENERAL):
    return f'''<footer><div class="footer-brand">SIMÓN ABOGADO<span>Compromiso que garantiza tu confianza.</span></div><div class="footer-nav"><a href="{base}#servicios">Encuentra tu servicio</a><a href="{base}#simon">Conoce a tu abogado</a><a class="footer-back-top" href="#inicio-pagina">Volver arriba ↑</a></div><div class="footer-social"><span class="footer-social-label">Conecta con nosotros</span><a href="https://www.facebook.com/profile.php?id=61595132795227" target="_blank" rel="noopener noreferrer" aria-label="Simón Abogado en Facebook (abre en una pestaña nueva)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 22v-9h3l.5-3.5h-3.5V7.25c0-1 .3-1.75 1.75-1.75H17V2.4c-.3-.05-1.35-.15-2.6-.15-2.6 0-4.4 1.6-4.4 4.55v2.7H7V13h3v9z"/></svg><span>Facebook</span></a><a href="https://www.tiktok.com/@garantiacol_abogados" target="_blank" rel="noopener noreferrer" aria-label="Garantíacol Abogados en TikTok (abre en una pestaña nueva)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 2h-3v13a3 3 0 1 1-3-3V9a6 6 0 1 0 6 6V8a9 9 0 0 0 5 1.5v-3A5 5 0 0 1 16 2z"/></svg><span>TikTok</span></a></div><p>© 2026 Simón Abogado · Atención jurídica con Klende Simon Villa</p></footer><a class="whatsapp-float" href="{contact_url}" target="_blank" rel="noopener noreferrer" aria-label="Cuéntame tu caso por WhatsApp (abre en una pestaña nueva)" title="Hablar por WhatsApp"><span class="whatsapp-label">Cuéntame tu caso</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.52 3.48A11.86 11.86 0 0 0 12.06 0C5.48 0 .12 5.35.12 11.93c0 2.1.55 4.16 1.6 5.97L0 24l6.26-1.64a11.94 11.94 0 0 0 5.8 1.48h.01C18.65 23.84 24 18.49 24 11.91c0-3.18-1.24-6.18-3.48-8.43ZM12.07 21.83a9.9 9.9 0 0 1-5.05-1.38l-.36-.21-3.72.98.99-3.63-.24-.38a9.89 9.89 0 0 1-1.51-5.28c0-5.46 4.44-9.9 9.91-9.9a9.84 9.84 0 0 1 7 2.9 9.83 9.83 0 0 1 2.9 7c0 5.47-4.44 9.9-9.92 9.9Zm5.44-7.42c-.3-.15-1.76-.87-2.04-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.47-2.4-1.48-.89-.79-1.49-1.77-1.66-2.07-.18-.3-.02-.46.13-.61.14-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.08-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.22 3.09c.15.2 2.1 3.21 5.08 4.5.71.3 1.26.49 1.69.63.71.23 1.36.2 1.87.12.57-.08 1.76-.72 2.01-1.42.25-.69.25-1.29.17-1.41-.07-.13-.27-.2-.57-.35Z"/></svg></a><script src="{base}app.js"></script></body></html>'''

def faqs(items):
    return '<div class="faq-list">' + ''.join(f'<details><summary>{q}<span class="plus" aria-hidden="true"></span></summary><p>{a}</p></details>' for q,a in items) + '</div>'

def steps(items):
    return '<div class="steps">' + ''.join(f'<article><span class="step-label">0{i}</span><h3>{t}</h3><p>{p}</p></article>' for i,(t,p) in enumerate(items,1)) + '</div>'

cards=[]
for s in SERVICES:
    route=f'servicios/{s["slug"]}/'
    cards.append(f'''<article class="service-card"><a class="service-cover" href="{route}" aria-label="Conocer el servicio de {s['name'].lower()}"><img src="assets/servicios/{s['image']}.webp" alt="{s['alt']}" width="1536" height="1024" loading="lazy" decoding="async"></a><div class="card-copy"><p class="card-label">{s['name'].upper()}</p><h3>{s['title']}</h3><p>{s['brief']}</p><a class="text-link" href="{route}" aria-label="Conocer el servicio de {s['name'].lower()}">Conocer este servicio <span aria-hidden="true">↗</span></a></div></article>''')

home=head('Tu tranquilidad merece un camino claro', '¿Deudas, cobros, contratos o una situación familiar? Encuentra orientación jurídica directa con Klende Simon Villa para entender tus opciones y decidir cómo avanzar.')+f'''
<main id="contenido"><section class="hero" id="inicio"><div class="hero-copy"><p class="eyebrow light">ORIENTACIÓN JURÍDICA PARA TU SIGUIENTE PASO</p><h1>Tu tranquilidad<br>merece un<br><em>camino claro.</em></h1><p class="hero-intro">Una deuda que no te deja dormir. Un pago que no llega. Una decisión que afecta a tu familia. No tienes que resolver todas tus dudas a solas: entiende tus opciones y decide cómo avanzar.</p>{wa(GENERAL,'Quiero contar mi situación')}<div class="hero-note"><span class="short-line" aria-hidden="true"></span><p>Habla directamente con Klende Simon Villa.<br>Empecemos por lo que hoy te preocupa.</p></div></div><figure class="portrait"><img src="assets/simon.jpg" alt="Klende Simon Villa, abogado" width="1086" height="1448" fetchpriority="high"><figcaption><span>Tu historia merece ser escuchada.</span><small>KLENDE SIMON VILLA · ABOGADO</small></figcaption></figure></section>
<div class="principles" aria-label="Lo que puedes esperar"><span>Tu situación, escuchada con atención</span><span>Tus opciones, explicadas con claridad</span><span>Tu siguiente paso, con orientación</span></div>
<section class="section services" id="servicios"><div class="section-heading"><div><p class="eyebrow">EMPIEZA POR LO QUE TE PREOCUPA</p><h2>¿Qué necesitas<br>resolver hoy?</h2></div><p>Encuentra la situación que más se parece a la tuya. Conoce cómo podemos abordarla y qué información ayuda a dar el primer paso.</p></div><div class="service-grid">{''.join(cards)}</div><div class="service-footer"><p>¿No sabes en qué servicio encaja tu situación?</p>{wa(GENERAL,'Cuéntamela y la revisamos','text-link')}</div></section>
<section class="approach section" id="simon"><div class="approach-statement"><p class="eyebrow">QUIÉN TE ACOMPAÑA</p><h2>Que te escuchen.<br>Que te expliquen.<br>Que puedas <em>decidir.</em></h2><p class="signature">Klende Simon Villa</p><span class="signature-caption">TU ABOGADO · ATENCIÓN DIRECTA</span></div><div class="approach-copy"><p class="lead">Experiencia que inspira confianza. Claridad para actuar.</p><p>Soy <strong>Klende Simon Villa</strong>, abogado con <strong>más de cinco años de experiencia</strong>. Sé que detrás de una consulta hay algo que quieres proteger: tu tranquilidad, tu familia o el patrimonio que has construido con esfuerzo.</p><p>Mi trabajo combina <strong>análisis jurídico, capacidad de negociación y atención al detalle</strong> para estudiar tu situación, identificar alternativas y ayudarte a tomar decisiones informadas. Te explico lo que necesitas saber con claridad, para que comprendas tus opciones y el propósito de cada paso.</p><p>Encontrarás <strong>escucha, trato cercano y atención directa</strong>. Desde el comienzo hablaremos de las posibilidades de tu caso, las dificultades que debemos considerar y cómo puedo acompañarte.</p><p>Quiero que tengas la tranquilidad de sentirte acompañado, la confianza de entender tus decisiones y una ruta clara para actuar.</p><div class="commitment">Compromiso que garantiza tu confianza.</div></div></section>
<section class="process section" id="proceso"><div class="section-heading"><div><p class="eyebrow">EL OBJETIVO DE REVISAR TU CASO</p><h2>Avanza con<br>tres cosas claras.</h2></div><p>No necesitas conocer el lenguaje jurídico para empezar. La revisión busca ayudarte a responder estas tres preguntas.</p></div>{steps([('¿Qué opciones tengo?', 'Entender las alternativas que podrían aplicar a tu situación y los aspectos que conviene evaluar.'),('¿Qué necesito reunir?', 'Identificar los documentos y la información necesarios para estudiar el caso y sustentar el siguiente paso.'),('¿Cómo puedo avanzar?', 'Conocer el alcance del acompañamiento, sus costos y los pasos propuestos para tomar una decisión informada.')])}</section>
<section class="questions section"><div><p class="eyebrow">ANTES DE DAR EL PRIMER PASO</p><h2>Resolvamos<br>tus primeras dudas.</h2></div>{faqs([('¿Necesito saber qué trámite me corresponde?', 'No. Empieza por contar qué ocurre y qué necesitas resolver. La revisión permite identificar el asunto y la información que hace falta.'),('¿Qué sucede cuando escribo por WhatsApp?', 'Puedes explicar brevemente tu situación e indicar el servicio que te interesa. A partir de ahí coordinamos cómo revisar tu caso y te informamos las condiciones de la asesoría.'),('¿Cuánto cuesta el acompañamiento?', 'Depende del servicio y del alcance que requiera tu caso. Los honorarios y las condiciones se explican antes de contratar para que puedas decidir con esa información.'),('¿Y si todavía no tengo todos los documentos?', 'Puedes empezar con una explicación de lo que pasa y los documentos que ya tienes. Después identificamos qué información adicional se necesita.'),('¿Pueden garantizarme un resultado?', 'Cada caso tiene condiciones propias. El compromiso es estudiar tu situación, explicarte las opciones y definir un acompañamiento claro; el resultado de un proceso no se puede asegurar de antemano.')])}</section>
<section class="contact" id="consulta"><p class="eyebrow light">TU PRIMER PASO PUEDE SER UNA CONVERSACIÓN</p><h2>Deja de darle vueltas.<br><em>Empieza por entender.</em></h2><p>Cuéntame qué está pasando y qué necesitas resolver. Organicemos tus dudas para decidir el siguiente paso.</p>{wa(GENERAL,'Quiero hablar con Klende Simon Villa')}<span class="contact-note">Por WhatsApp · Atención directa · Condiciones claras antes de contratar</span></section></main>'''+footer()
(ROOT/'index.html').write_text(home,encoding='utf-8')

for s in SERVICES:
    base='../../'
    url='https://wa.link/'+s['wa']
    page=head(s['name'],s['brief'],base)+f'''<main id="contenido"><section class="detail-hero"><div class="detail-intro"><a class="back-link" href="../../#servicios">← Explorar todos los servicios</a><p class="eyebrow light">{s['name'].upper()}</p><h1>{s['title']}</h1><p>{s['intro']}</p>{wa(url,s['cta'])}</div><figure class="detail-image"><img src="../../assets/servicios/{s['image']}.webp" alt="{s['alt']}" width="1536" height="1024" fetchpriority="high"></figure></section>
<section class="section detail-context"><div><p class="eyebrow">TU SITUACIÓN ES EL PUNTO DE PARTIDA</p><h2>Tal vez esto se parece<br>a lo que estás viviendo.</h2><p class="intro-text">No necesitas tener todas las respuestas. Empezamos por entender el problema que quieres resolver.</p></div><ul class="situation-list">{''.join('<li>'+v+'</li>' for v in s['situations'])}</ul></section>
<section class="section detail-outcomes"><div class="section-heading"><div><p class="eyebrow">CÓMO PUEDE AYUDARTE LA REVISIÓN</p><h2>Tres puntos para<br>decidir con claridad.</h2></div><p>Con atención directa de Klende Simon Villa, explicaciones comprensibles y un alcance definido según tu caso.</p></div>{steps(s['outcomes'])}<p class="scope-note">Las alternativas y la viabilidad de cualquier actuación dependen de los documentos y las condiciones de tu situación.</p></section>
<section class="section prepare"><div><p class="eyebrow">PREPARA LA PRIMERA CONVERSACIÓN</p><h2>Empieza con<br>lo que ya sabes.</h2></div><div class="prepare-copy"><p>{s['prepare']}</p><p>Antes de contratar, conocerás el alcance del servicio, los honorarios y las condiciones del acompañamiento.</p>{wa(url,s['cta'],'text-link')}</div></section>
<section class="questions section"><div><p class="eyebrow">DUDAS SOBRE ESTE SERVICIO</p><h2>Lo que quizá<br>te estás preguntando.</h2></div>{faqs(s['faq'])}</section>
<section class="contact detail-contact"><p class="eyebrow light">HABLEMOS DE TU SITUACIÓN</p><h2>{s['close']}</h2><p>No hace falta que sepas por dónde empezar. Cuéntame qué ocurre y qué te gustaría aclarar.</p>{wa(url,s['cta'])}<span class="contact-note">Habla directamente con Klende Simon Villa · Cuéntame qué necesitas resolver</span><a class="other-service" href="../../#servicios">Explorar otro servicio</a></section></main>'''+footer(base,url)
    folder=ROOT/'servicios'/s['slug']
    folder.mkdir(parents=True,exist_ok=True)
    (folder/'index.html').write_text(page,encoding='utf-8')
print('Contenido generado: inicio y seis páginas de servicios.')
